# Generated by Django 4.1.2 on 2022-10-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_cart_profile_alter_cartproduct_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Paystack', 'Paystack')], default='Cash on delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='ref',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
